- name: install/uninstall/upgrade s/w applications
  hosts: all
  tasks:
    - name: install,upgrade,uninstall s/w's
      apt:
        name: "{{item.a}}"
        state: "{{item.b}}"
        update_cache: "{{item.c}}"
      with_items:
            - { a: tree, b: present, c: yes}
            - { a: git, b: absent, c: no} 
            - { a: maven, b: latest, c: no}      
