---
- name: configuring apache2
  hosts: all
  tasks:
    - name: install apache2
      apt:
        name: apache2
        state: present
        update_cache: yes
    - name: edit the index.html file
      copy:
        content: "A FILM  BY KAREEM"
        dest: /var/www/html/index.html
    - name: restart apache2
      service:
        name: apache2
        state: restarted
    - name: check apache2 cofiguration server1
      uri:
       url: http://172.31.21.3
       status_code: 200
    - name: check apache2 configuration server2
      uri: 
       url: http://172.31.30.50
       status_code: 200

          
